Link in new tab (#477)
cobrateam/splinter pull request #800
Opened 2020-09-06 19:07 UTC by szafran98

Added new_tab method to BaseWebDriver (#477 ). It needs to execute some javascript code to change browser preferences, because at default firefox open all links even with `_blank` in a new window. Every other method which i found aren't changing preferences if browser already running. Other possibility is to add `firefox_profile.set_preference("browser.link.open_newwindow", 3)` in `firefox.py`.

2020-09-06 22:24 UTC, szafran98 commented
I've run tests on fresh clone and there are still errors. How to exclude django and flask from tests, because i don't think that it is possible to evaluate javascript code in their client, but maybe i put the code in bad place.
```
FAILED tests/test_webdriver_firefox.py::FirefoxBrowserTest::test_clicking_submit_input_posts_empty_value_if_value_not_present - AssertionError: None is not true : 'submit-input-no-value: Wyślij ...
FAILED tests/test_webdriver_firefox.py::FirefoxBrowserFullScreenTest::test_clicking_submit_input_posts_empty_value_if_value_not_present - AssertionError: None is not true : 'submit-input-no-valu...
```

2020-09-07 23:19 UTC, andrewsmedina commented
@szafran98 how this method only makes sense for webdriver drivers, this test should be defined in `WebDriverTests ` (https://github.com/cobrateam/splinter/blob/8fff713ec2741dc9b98babe2a34bdc9666e96196/tests/base.py#L167) class  instead in the `BaseBrowserTests`.

2020-09-21 21:07 UTC, szafran98 commented
@andrewsmedina hey, can you review this?

2020-10-03 18:57 UTC, szafran98 commented
@andrewsmedina hey, can you give me any answer?

2020-10-22 18:58 UTC, szafran98 commented
@jsfehler hey, have you contact with @andrewsmedina ? Can someone review it?

2020-10-26 16:57 UTC, andrewsmedina commented
@szafran98 sorry for the delay. I believe that this PR looks good to me. Can you sync your branch with the master?

2020-10-29 17:38 UTC, jsfehler requested changes

2020-10-29 17:38 UTC, jsfehler commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove this file from your PR

2020-10-29 17:44 UTC, szafran98 commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Done

2020-10-31 18:01 UTC, szafran98 commented
Reopen for tests rerun

2020-11-02 13:50 UTC, szafran98 commented
@andrewsmedina hey, it's looking the tests are finally passed

2020-11-04 17:33 UTC, andrewsmedina commented
@szafran98 thanks for contribute

2020-11-04 17:33 UTC, merged